apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: jobflow

spec:
  selector:
    app: jobflow-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP
